// DetailsStep - Event details, title, description, tickets, fees
import { useState } from 'react';
import { Sparkles, FileText, Ticket, PoundSterling, ChevronDown, Wallet, Users } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import type { PublicGigFormData } from '@/components/public-gig-wizard';

interface DetailsStepProps {
  formData: PublicGigFormData;
  onUpdate: (data: Partial<PublicGigFormData>) => void;
  artistName: string;
}

export default function DetailsStep({ formData, onUpdate, artistName }: DetailsStepProps) {
  const [showTicketInfo, setShowTicketInfo] = useState(false);
  const [showFeeInfo, setShowFeeInfo] = useState(
    formData.agreedFee !== undefined || formData.actualFee !== undefined
  );

  // Auto-generate title if not manually edited
  const defaultTitle = formData.venueName ? `${artistName} @ ${formData.venueName}` : '';
  const showAutoGenerated = !formData.title || formData.title === defaultTitle;

  return (
    <div className="space-y-6">
      {/* Title */}
      <div>
        <label className="block text-sm font-semibold text-foreground mb-2">
          Event Title
          {showAutoGenerated && (
            <span className="ml-2 text-xs font-normal text-muted-foreground">
              (auto-generated)
            </span>
          )}
        </label>
        <div className="relative">
          <Sparkles className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-5 h-5" />
          <Input
            type="text"
            value={formData.title || defaultTitle}
            onChange={(e) => onUpdate({ title: e.target.value })}
            placeholder={`e.g., ${defaultTitle}`}
            className="pl-10 pr-4 min-h-[56px] md:min-h-[44px] text-base focus:border-orange-500 focus:ring-orange-500"
          />
        </div>
      </div>

      {/* Description */}
      <div>
        <label className="block text-sm font-semibold text-foreground mb-2">
          Description (Optional)
        </label>
        <div className="relative">
          <Textarea
            value={formData.description || ''}
            onChange={(e) => onUpdate({ description: e.target.value })}
            placeholder="Tell people about your gig..."
            rows={5}
            className="resize-none text-base focus:border-orange-500 focus:ring-orange-500"
          />
          <div className="absolute bottom-2 right-2 text-xs text-muted-foreground">
            {formData.description?.length || 0}/500
          </div>
        </div>
      </div>

      {/* Ticket Information - Collapsible */}
      <div className="border border-border rounded-xl overflow-hidden">
        <button
          type="button"
          onClick={() => setShowTicketInfo(!showTicketInfo)}
          className="w-full flex items-center justify-between p-4 hover:bg-accent/50 transition-colors"
        >
          <div className="flex items-center gap-2 text-sm font-semibold text-foreground">
            <Ticket className="w-4 h-4" />
            Ticket Information (Optional)
          </div>
          <ChevronDown className={`w-5 h-5 text-muted-foreground transition-transform ${showTicketInfo ? 'rotate-180' : ''}`} />
        </button>

        {showTicketInfo && (
          <div className="p-4 pt-0 space-y-4">
            {/* Ticket URL */}
            <div>
              <label className="block text-xs text-muted-foreground mb-2">
                Ticket URL
              </label>
              <Input
                type="url"
                value={formData.ticketUrl || ''}
                onChange={(e) => onUpdate({ ticketUrl: e.target.value })}
                placeholder="https://example.com/tickets"
                className="text-base min-h-[56px] md:min-h-[44px] focus:border-orange-500 focus:ring-orange-500"
              />
            </div>

            {/* Ticket Price */}
            <div>
              <label className="block text-xs text-muted-foreground mb-2">
                Ticket Price
              </label>
              <div className="relative">
                <PoundSterling className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
                <Input
                  type="text"
                  value={formData.ticketPrice || ''}
                  onChange={(e) => onUpdate({ ticketPrice: e.target.value })}
                  placeholder="Free / £10 / £5-£15"
                  className="pl-10 pr-4 text-base min-h-[56px] md:min-h-[44px] focus:border-orange-500 focus:ring-orange-500"
                />
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Fee Information - Collapsible (Private - Backstage Only) */}
      <div className="border border-border rounded-xl overflow-hidden">
        <button
          type="button"
          onClick={() => setShowFeeInfo(!showFeeInfo)}
          className="w-full flex items-center justify-between p-4 hover:bg-accent/50 transition-colors"
        >
          <div className="flex items-center gap-2 text-sm font-semibold text-foreground">
            <Wallet className="w-4 h-4" />
            <span>Fee Tracking</span>
            <span className="text-xs font-normal text-muted-foreground">(Private)</span>
          </div>
          <ChevronDown className={`w-5 h-5 text-muted-foreground transition-transform ${showFeeInfo ? 'rotate-180' : ''}`} />
        </button>

        {showFeeInfo && (
          <div className="p-4 pt-0 space-y-4">
            {/* Agreed Fee */}
            <div>
              <label className="block text-xs text-muted-foreground mb-2">
                Agreed Fee
              </label>
              <div className="relative">
                <PoundSterling className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
                <Input
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.agreedFee ?? ''}
                  onChange={(e) => {
                    const value = e.target.value ? parseFloat(e.target.value) : undefined;
                    onUpdate({
                      agreedFee: value,
                      // Auto-set actualFee to agreedFee if not already set
                      ...(formData.actualFee === undefined && value !== undefined ? { actualFee: value } : {})
                    });
                  }}
                  placeholder="0.00"
                  className="pl-10 pr-4 text-base min-h-[56px] md:min-h-[44px] focus:border-emerald-500 focus:ring-emerald-500"
                />
              </div>
            </div>

            {/* Actual Fee (only show if agreed fee is set) */}
            {formData.agreedFee !== undefined && (
              <div>
                <label className="block text-xs text-muted-foreground mb-2">
                  Actual Fee (if different)
                </label>
                <div className="relative">
                  <PoundSterling className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
                  <Input
                    type="number"
                    step="0.01"
                    min="0"
                    value={formData.actualFee ?? formData.agreedFee ?? ''}
                    onChange={(e) => {
                      const value = e.target.value ? parseFloat(e.target.value) : undefined;
                      onUpdate({ actualFee: value });
                    }}
                    placeholder={String(formData.agreedFee ?? '0.00')}
                    className="pl-10 pr-4 text-base min-h-[56px] md:min-h-[44px] focus:border-emerald-500 focus:ring-emerald-500"
                  />
                </div>
              </div>
            )}

            {/* Split Between Members Toggle */}
            <div className="flex items-center justify-between py-2">
              <div className="flex items-center gap-2">
                <Users className="w-4 h-4 text-muted-foreground" />
                <div>
                  <p className="text-sm font-medium text-foreground">Split between members</p>
                  <p className="text-xs text-muted-foreground">
                    Auto-create member payment expenses when paid
                  </p>
                </div>
              </div>
              <Switch
                checked={formData.splitBetweenMembers ?? false}
                onCheckedChange={(checked) => onUpdate({ splitBetweenMembers: checked })}
              />
            </div>

            <p className="text-xs text-muted-foreground italic">
              Fee details are only visible to band members in Backstage
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
