// DetailsStep - Event details, title, description, tickets
import { Sparkles, FileText, Ticket, PoundSterling } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import type { PublicGigFormData } from '@/components/public-gig-wizard';

interface DetailsStepProps {
  formData: PublicGigFormData;
  onUpdate: (data: Partial<PublicGigFormData>) => void;
  artistName: string;
}

export default function DetailsStep({ formData, onUpdate, artistName }: DetailsStepProps) {
  // Auto-generate title if not manually edited
  const defaultTitle = formData.venueName ? `${artistName} @ ${formData.venueName}` : '';
  const showAutoGenerated = !formData.title || formData.title === defaultTitle;

  return (
    <div className="space-y-6">
      {/* Title */}
      <div>
        <label className="block text-sm font-semibold text-foreground mb-2">
          Event Title
          {showAutoGenerated && (
            <span className="ml-2 text-xs font-normal text-muted-foreground">
              (auto-generated, editable)
            </span>
          )}
        </label>
        <div className="relative">
          <Sparkles className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-5 h-5" />
          <Input
            type="text"
            value={formData.title || defaultTitle}
            onChange={(e) => onUpdate({ title: e.target.value })}
            placeholder={`e.g., ${defaultTitle}`}
            className="pl-10 pr-4 min-h-[56px] md:min-h-[44px] text-base"
          />
        </div>
        <p className="text-xs text-muted-foreground mt-2">
          This is what fans will see on bndy.live and social media
        </p>
      </div>

      {/* Description */}
      <div>
        <label className="block text-sm font-semibold text-foreground mb-2">
          Description (Optional)
        </label>
        <div className="relative">
          <Textarea
            value={formData.description || ''}
            onChange={(e) => onUpdate({ description: e.target.value })}
            placeholder="Tell people about your gig... Special guests? Cover charge? Themed night?"
            rows={5}
            className="resize-none text-base"
          />
          <div className="absolute bottom-2 right-2 text-xs text-muted-foreground">
            {formData.description?.length || 0}/500
          </div>
        </div>
        <p className="text-xs text-muted-foreground mt-2">
          Add details like support acts, door prices, dress code, etc.
        </p>
      </div>

      {/* Ticket Information */}
      <div className="border border-border rounded-xl p-4 space-y-4">
        <div className="flex items-center gap-2 text-sm font-semibold text-foreground mb-3">
          <Ticket className="w-4 h-4" />
          Ticket Information (Optional)
        </div>

        {/* Ticket URL */}
        <div>
          <label className="block text-xs text-muted-foreground mb-2">
            Ticket URL
          </label>
          <Input
            type="url"
            value={formData.ticketUrl || ''}
            onChange={(e) => onUpdate({ ticketUrl: e.target.value })}
            placeholder="https://example.com/tickets"
            className="text-base min-h-[56px] md:min-h-[44px]"
          />
        </div>

        {/* Ticket Price */}
        <div>
          <label className="block text-xs text-muted-foreground mb-2">
            Ticket Price
          </label>
          <div className="relative">
            <PoundSterling className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
            <Input
              type="text"
              value={formData.ticketPrice || ''}
              onChange={(e) => onUpdate({ ticketPrice: e.target.value })}
              placeholder="Free / £10 / £5-£15"
              className="pl-10 pr-4 text-base min-h-[56px] md:min-h-[44px]"
            />
          </div>
          <p className="text-xs text-muted-foreground mt-1">
            e.g., "Free", "£10", "£5-£15", "£10 adv / £12 door"
          </p>
        </div>
      </div>

      {/* Helper Text */}
      <div className="text-sm text-muted-foreground bg-muted/50 rounded-lg p-4">
        <p className="font-medium mb-2">💡 Tip</p>
        <ul className="space-y-1 text-xs">
          <li>• All fields on this page are <strong>optional</strong></li>
          <li>• Title auto-generated as "{defaultTitle}" but you can change it</li>
          <li>• Add ticket info to help fans find tickets easily</li>
        </ul>
      </div>
    </div>
  );
}
